/**
 * InfraSight TypeScript Types
 * ============================
 * Shared domain types used across components, API client, and hooks.
 * Mirrors the Pydantic schemas on the backend.
 */

import type { LucideIcon } from "lucide-react";

/** Navigation section names shown in the sidebar. */
export type Section =
  | "Dashboard"
  | "Alerts"
  | "OpenClaw"
  | "Servers"
  | "Databases"
  | "Containers"
  | "Kubernetes"
  | "Topology"
  | "Connectors"
  | "Inventory"
  | "Automation"
  | "Notifications"
  | "Administration";

export type ResourceMetadataValue =
  | string
  | number
  | boolean
  | null
  | ResourceMetadataValue[]
  | { [key: string]: ResourceMetadataValue };

// ---------------------------------------------------------------------------
// Infrastructure resources
// ---------------------------------------------------------------------------

/** A discovered or synchronized infrastructure asset (EC2, VM, host, container, DB). */
export type Resource = {
  id: number | string;
  tenant_id?: string;
  organization_id?: string;
  resource_id?: string;
  provider: string;
  resource_type: string;
  platform?: string | null;
  name: string;
  region: string;
  status: string;
  private_ip?: string | null;
  metadata?: Record<string, ResourceMetadataValue>;
  health_score?: number;
  health_status?: ResourceHealthStatus;
  monitoring_status?: string;
};

export type ResourceHealthStatus = "Healthy" | "Warning" | "Critical";

// ---------------------------------------------------------------------------
// Alerts and monitoring
// ---------------------------------------------------------------------------

/** A monitoring alert generated by the alert evaluation engine. */
export type AlertRecord = {
  id: number | string;
  tenant_id?: string;
  organization_id?: string;
  resource_id?: number | string;
  fingerprint?: string | null;
  title: string;
  description?: string | null;
  severity: string;
  status: string;
  source: string;
  metric_name?: string | null;
  metric_value?: number | null;
  threshold?: number | null;
  created_at?: string;
  first_seen_at?: string | null;
  last_seen_at?: string | null;
  updated_at?: string | null;
  acknowledged_at?: string | null;
  investigating_at?: string | null;
  resolved_at?: string | null;
  closed_at?: string | null;
  archived_at?: string | null;
  assigned_to?: string | null;
  investigation_notes?: string | null;
  resolution_notes?: string | null;
  root_cause?: string | null;
  resolution_category?: string | null;
  resolved_by?: string | null;
  closed_by?: string | null;
  success_rating?: number | null;
  metadata?: Record<string, ResourceMetadataValue>;
};

export type AlertStatus = "open" | "acknowledged" | "investigating" | "resolved" | "closed";

export type AlertStatusUpdate = {
  status: AlertStatus;
  investigation_notes?: string;
  resolution_notes?: string;
  root_cause?: string;
  resolution_category?: string;
  resolved_by?: string;
  success_rating?: number;
};

/** Connector health status used by the Overview and OpenClaw operational summary. */
export type ConnectorHealth = {
  connector_type: string;
  label: string;
  status: string;
  resources: number;
  metrics: number;
  alerts: number;
  capabilities: string[];
  message: string;
};

export type ConnectorStatus = "Connected" | "Degraded" | "Failed" | "Ready";

export type ConnectorCatalogCapability = {
  key: string;
  label: string;
};

export type ConnectorCatalogItem = {
  connector_type: string;
  label: string;
  platform: string;
  description: string;
  supports_agents: boolean;
  capabilities: ConnectorCatalogCapability[];
};

export type ConnectorRegistration = {
  id: number;
  tenant_id: string;
  organization_id: string;
  connector_type: string;
  name: string;
  status: string;
  config: Record<string, ResourceMetadataValue>;
  last_status: string;
  last_checked_at?: string | null;
  created_at: string;
  updated_at?: string | null;
};

export type ConnectorInstance = {
  id: number;
  workspace_id: number;
  provider: string;
  connection_type: string;
  status: string;
  health: Record<string, ResourceMetadataValue>;
  configuration: Record<string, ResourceMetadataValue>;
  last_sync?: string | null;
  created_at: string;
  updated_at?: string | null;
};

export type ConnectorInstancePayload = {
  provider: string;
  connection_type: string;
  status?: string;
  health?: Record<string, ResourceMetadataValue>;
  configuration?: Record<string, ResourceMetadataValue>;
  credentials?: Array<{ type: string; value: string }>;
};

export type DiscoveredConnectorResource = {
  id: number;
  connector_id: number;
  provider: string;
  resource_type: string;
  name: string;
  metadata: Record<string, ResourceMetadataValue>;
  health: Record<string, ResourceMetadataValue>;
  status: string;
  last_seen: string;
};

export type ConnectorOperationResult = {
  operation: string;
  status: string;
  outcome: string;
  message: string;
  connector: ConnectorInstance;
  resources: DiscoveredConnectorResource[];
  sync?: {
    id: number;
    connector_id: number;
    started_at: string;
    finished_at?: string | null;
    status: string;
    resources_discovered: number;
    error_message?: string | null;
  } | null;
};

/** Cross-provider operational summary returned by /monitoring/operational-summary. */
export type OperationalSummary = {
  status: string;
  tenant_id: string;
  resources: {
    total: number;
    by_provider: Record<string, number>;
  };
  alerts: {
    open: number;
    by_connector: Record<string, number>;
    by_severity: Record<string, number>;
  };
  agent_ready: boolean;
  kubernetes_ready: boolean;
};

// ---------------------------------------------------------------------------
// Discovery
// ---------------------------------------------------------------------------

/** A single discovery run record tracking status, counts, and errors. */
export type DiscoveryRun = {
  id: number;
  tenant_id: string;
  organization_id: string;
  discovery_type: string;
  trigger: string;
  status: string;
  assets_discovered: number;
  assets_created: number;
  assets_updated: number;
  relationships_created: number;
  started_at: string;
  completed_at?: string | null;
  error?: string | null;
  metadata?: Record<string, unknown>;
};

/** Discovery coverage summary returned by /discovery/summary. */
export type DiscoverySummary = {
  supported_types: string[];
  recent_runs: DiscoveryRun[];
  topology_relationships: number;
  monitoring_profiles: Record<string, number>;
  agent_ready: boolean;
  event_driven_ready: boolean;
  kubernetes_ready: boolean;
};

// ---------------------------------------------------------------------------
// Metrics
// ---------------------------------------------------------------------------

/** A single time-series metric sample collected from a resource. */
export type MetricSample = {
  id: number;
  tenant_id?: string;
  organization_id?: string;
  resource_id: number;
  metric_name: string;
  value: number;
  unit: string;
  collected_at: string;
};

export type LogEntry = {
  id: number | string;
  workspace_id: string;
  connector_id?: number | null;
  resource_id?: number | string | null;
  source: string;
  severity: string;
  message: string;
  timestamp: string;
  metadata?: Record<string, ResourceMetadataValue>;
};

export type SyncRun = {
  id: number | string;
  workspace_id: string;
  connector_id?: number | null;
  connector_type: string;
  status: "running" | "success" | "failed" | "partial";
  started_at: string;
  completed_at?: string | null;
  resources_collected: number;
  metrics_collected: number;
  logs_collected: number;
  alerts_created: number;
  error?: string | null;
};

export type RecentActivityItem = {
  id: string;
  type:
    | "alert_triggered"
    | "alert_resolved"
    | "resource_discovered"
    | "resource_removed"
    | "monitoring_state";
  title: string;
  detail: string;
  severity: "critical" | "warning" | "success" | "info";
  timestamp?: string;
};

/** Aggregate monitoring health summary returned by /monitoring/summary. */
export type MonitoringSummary = {
  total_resources: number;
  healthy_percentage: number;
  running_percentage: number;
  open_alerts: number;
  critical_alerts: number;
  warning_alerts: number;
};

// ---------------------------------------------------------------------------
// Notifications
// ---------------------------------------------------------------------------

export type NotificationChannelType = "email" | "slack" | "teams";

/** A configured notification destination (email address, Slack webhook, etc.). */
export type NotificationChannel = {
  id: number;
  tenant_id?: string;
  organization_id?: string;
  name: string;
  channel_type: NotificationChannelType;
  target: string;
  enabled: boolean;
  last_status: string;
  created_at?: string;
  last_test_at?: string | null;
  last_test_result?: string | null;
  last_test_error?: string | null;
};

/** A record of an alert notification delivery attempt. */
export type AlertDelivery = {
  id: number;
  tenant_id?: string;
  organization_id?: string;
  alert_id?: number | null;
  channel_id?: number | null;
  channel_type: string;
  target: string;
  status: string;
  detail?: string | null;
  response_time_ms?: number | null;
  sent_at: string;
};

/** SMTP server configuration for outbound email alerts. Password is never returned. */
export type SmtpConfig = {
  is_configured: boolean;
  host?: string | null;
  port: number;
  username?: string | null;
  has_password: boolean;
  from_email: string;
  use_tls: boolean;
  last_test_at?: string | null;
  last_test_result?: string | null;
  last_test_error?: string | null;
};

/** Payload for saving SMTP settings. Omit password to keep the existing value. */
export type SmtpConfigUpdate = {
  host?: string | null;
  port?: number;
  username?: string | null;
  password?: string | null;
  from_email?: string;
  use_tls?: boolean;
};

/** Form payload for creating a new notification channel. */
export type ChannelForm = {
  name: string;
  channel_type: NotificationChannelType;
  target: string;
};

// ---------------------------------------------------------------------------
// Organizations / multi-client management
// ---------------------------------------------------------------------------

/** An organization (tenant) record. */
export type Organization = {
  id: number;
  tenant_id: string;
  name: string;
  status: string;
  created_at: string;
};

/** The tenant context returned by /organizations/context for the current request. */
export type OrganizationContext = {
  tenant_id: string;
  organization_id: string;
  organization_name: string;
  role: string;
  is_msp_admin: boolean;
  permissions: string[];
};

// ---------------------------------------------------------------------------
// Authentication / SSO
// ---------------------------------------------------------------------------

export type AuthWorkspace = {
  id: string;
  name: string;
  role: string;
};

export type AuthUser = {
  id: number;
  email: string;
  role: string;
  workspace_id: string;
  organization_id: string;
  workspaces: AuthWorkspace[];
};

export type AuthSession = {
  authenticated: boolean;
  user: AuthUser;
  expires_in_minutes: number;
};

export type SsoProviderType = "SAML" | "OIDC";
export type InfrasightRole = "admin" | "operator" | "viewer";

export type SsoProviderConfig = {
  id: number;
  provider_name: string;
  provider_type: SsoProviderType;
  entity_id?: string | null;
  client_id?: string | null;
  sso_url?: string | null;
  authorization_url?: string | null;
  metadata_url?: string | null;
  callback_url?: string | null;
  workspace_id: string;
  enabled: boolean;
  auto_provisioning_enabled: boolean;
  allowed_domains: string[];
  default_role: InfrasightRole;
  role_mapping: Record<string, InfrasightRole>;
  scim: Record<string, ResourceMetadataValue>;
  has_certificate: boolean;
  has_client_secret: boolean;
  masked_certificate?: string | null;
  masked_client_secret?: string | null;
  last_test_at?: string | null;
  last_test_result?: string | null;
  last_test_error?: string | null;
  created_at: string;
  updated_at?: string | null;
};

export type SsoProviderConfigPayload = {
  provider_name: string;
  provider_type: SsoProviderType;
  entity_id?: string;
  client_id?: string;
  sso_url?: string;
  authorization_url?: string;
  metadata_url?: string;
  callback_url?: string;
  workspace_id: string;
  enabled: boolean;
  auto_provisioning_enabled: boolean;
  allowed_domains: string[];
  default_role: InfrasightRole;
  role_mapping: Record<string, InfrasightRole>;
  scim: Record<string, ResourceMetadataValue>;
  certificate?: string;
  client_secret?: string;
};

export type SsoStartResponse = {
  status: string;
  provider_name?: string | null;
  provider_type?: string | null;
  redirect_url?: string | null;
  message: string;
};

export type ManagedUserStatus = "invited" | "active" | "disabled";
export type ManagedUserAuthType = "local" | "sso";

export type ManagedUser = {
  id: number;
  email: string;
  display_name?: string | null;
  role: InfrasightRole;
  workspace_ids: string[];
  auth_type: ManagedUserAuthType;
  status: ManagedUserStatus;
  last_login_at?: string | null;
};

export type ManagedUserInvite = {
  email: string;
  display_name?: string;
  role: InfrasightRole;
  workspace_ids: string[];
  auth_type: ManagedUserAuthType;
};

export type ManagedUserUpdate = {
  display_name?: string;
  role?: InfrasightRole;
  workspace_ids?: string[];
  status?: ManagedUserStatus;
};

// ---------------------------------------------------------------------------
// OpenClaw AI providers
// ---------------------------------------------------------------------------

export type AiProviderType =
  | "builtin"
  | "openai_compatible"
  | "azure_openai"
  | "anthropic"
  | "ollama"
  | "custom_http";

export type AiProviderStatus = "Connected" | "Failed" | "Not Configured";

export type AiProviderConfig = {
  id: number;
  provider_name: string;
  provider_type: AiProviderType;
  base_url?: string | null;
  model_name?: string | null;
  enabled: boolean;
  is_active: boolean;
  workspace_id: string;
  has_secret: boolean;
  masked_secret?: string | null;
  status: AiProviderStatus;
  last_test_at?: string | null;
  last_test_result?: string | null;
  last_test_error?: string | null;
  created_at: string;
  updated_at?: string | null;
};

export type AiProviderConfigPayload = {
  provider_name: string;
  provider_type: AiProviderType;
  base_url?: string;
  api_secret?: string;
  model_name?: string;
  enabled: boolean;
  is_active: boolean;
  workspace_id: string;
};

export type AiProviderTestResult = {
  status: AiProviderStatus;
  detail: string;
  checked_at: string;
  provider: AiProviderConfig;
};

// ---------------------------------------------------------------------------
// Workspace context
// ---------------------------------------------------------------------------

export type Workspace = {
  id: string;
  organization_id: string;
  organization_name: string;
  name: string;
  environment: string;
  status: string;
  resource_count: number;
  alert_count: number;
  health_score: number;
};

export type WorkspaceGroup = {
  organization_id: string;
  organization_name: string;
  workspaces: Workspace[];
};

export type WorkspaceContextValue = {
  activeWorkspace: Workspace;
  groups: WorkspaceGroup[];
  workspaces: Workspace[];
};

// ---------------------------------------------------------------------------
// Shared UI / charting types
// ---------------------------------------------------------------------------

export type ChartDatum = {
  name: string;
  value: number;
};

export type NavigationItem = {
  name: Section;
  icon: LucideIcon;
};

export type NavigationGroup = {
  label: string;
  items: NavigationItem[];
};

// ---------------------------------------------------------------------------
// Topology graph
// ---------------------------------------------------------------------------

/** A single node in the infrastructure topology graph. */
export type TopologyNode = {
  id: number;
  name: string;
  resource_type: string;
  provider: string;
  region: string;
  status: string;
  health_status: string;
  alert_count: number;
  critical_alert_count: number;
  metadata?: Record<string, ResourceMetadataValue>;
};

/** A directed relationship edge between two topology nodes. */
export type TopologyEdge = {
  id: string;
  source_id: number;
  target_id: number;
  relationship_type: string;
  inferred: boolean;
  metadata?: Record<string, ResourceMetadataValue>;
};

/** Complete topology graph returned by /topology/graph. */
export type TopologyGraph = {
  nodes: TopologyNode[];
  edges: TopologyEdge[];
};

// ---------------------------------------------------------------------------
// Dashboard snapshot
// ---------------------------------------------------------------------------

/** Complete dashboard data bundle fetched in a single parallel batch. */
export type InfraSightSnapshot = {
  resources: Resource[];
  summary: MonitoringSummary;
  alerts: AlertRecord[];
  metrics: MetricSample[];
  channels: NotificationChannel[];
  deliveries: AlertDelivery[];
};
